piVersion: v1
kind: Service
metadata:
  name: myapp-sts
  labels:
    app: myapp-sts
spec:
  ports:
  - port: 80
    name: web
  clusterIP: "None"
  selector:
    app: myapp-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  serviceName: myapp-sts-svc
  replicas: 2
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
      - name: nginx
        image: dockerhub.azk8s.cn/library/nginx:alpine
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu : 30m
            memory: 50Mi
        volumeMounts:
        - name: myappdata
          mountPath: /var/lib/nginx/
  volumeClaimTemplates:
  - metadata:
      name: myappdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
